title : 有关五条人
name: '有关五条人'
description: '有关五条人'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

collections:
  posts:
    title: Essays
    default_open: true
    output: true
  interviews:
    title: 访谈
    default_open: true
    output: true
  songs:
    title: 歌曲
    default_open: true
    output: true
  works:
    title: 发表图文
    default_open: true
    output: true
  videos:
    title: 视频
    default_open: true
    output: true
  reports:
    title: 报道
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: Interviews
    values:
      title: 访谈
      permalink: /interviews/:title
  - scope:
      type: Songs
    values:
      title: 歌曲
      permalink: /songs/:title
  - scope:
      type: Works
    values:
      title: 发表图文
      permalink: /works/:title
  - scope:
      type: Videos
    values:
      title: 视频
      permalink: /videos/:title
  - scope:
      type: Reports
    values:
      title: 报道
      permalink: /reports/:title

plugins:
  - jekyll-sitemap

cdn: "https://cdn.jsdelivr.net/gh/wutiaoreninfo/wutiaoreninfo.github.io@main"
#cdn: ""