title : 有关五条人
name: '有关五条人'
description: '关于五条人的专辑、现场视频、访谈、报道、评论等内容'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

url: https://wutiaoren.info
baseurl: ""

collections:
  posts:
    title: Essays
    default_open: true
    output: true
  interviews:
    title: 访谈
    default_open: true
    output: true
  songs:
    title: 歌曲
    default_open: true
    output: true
  albums:
    title: 专辑
    default_open: true
    output: true
  works:
    title: 发表图文
    default_open: true
    output: true
  videos:
    title: 视频
    default_open: true
    output: true
  reports:
    title: 报道
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: Interviews
    values:
      title: 访谈
      permalink: /interviews/:title
  - scope:
      type: Songs
    values:
      title: 歌曲
      permalink: /songs/:title
  - scope:
      type: Albums
    values:
      title: 专辑
      permalink: /albums/:title
  - scope:
      type: Works
    values:
      title: 发表图文
      permalink: /works/:title
  - scope:
      type: Videos
    values:
      title: 视频
      permalink: /videos/:title
  - scope:
      type: Reports
    values:
      title: 报道
      permalink: /reports/:title

plugins:
  - jekyll-sitemap

cdn: "https://cdn.jsdelivr.net/gh/wutiaoreninfo/wutiaoreninfo.github.io@main"
#cdn: ""

# config for Algolia search
algolia:
   application_id: "VW8QVTARD0"
   index_name: "wutiaoreninfo"
   search_only_api_key: "765ff1a9af7b41c2f85e863463b10ea9"
   extensions_to_index: 
      - html
      - md
   nodes_to_index: 'p,blockquote,li,tr'
   files_to_exclude: [index.html,search.html,changelog.md,changelog.html]
   hitsPerPage: 1000

exclude: [vendor]
